# Use postgres/example user/password credentials
services:
  db-tsoha:
    image: tsoha-film
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    network_mode: "host"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tsoha-film
  
  adminer:
    network_mode: "host"
    image: adminer
